version: '3'

networks:
  default:
    external:
      name: proxy

services:
    
  nuxt:
    build: 
      context: .
      dockerfile: Dockerfile.nuxt
    ports:
      - "8080:8080"
    command: npm run start