version: "3"

networks:
  default:
    external:
      name: proxy

services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile.nuxt
    container_name: admin_front
    hostname: admin_front
    ports:
      - "8080:8080"
    command: npm run start
