version: '3'

networks:
  api:
  client:

services:

  nginx:
    image: 'nginx:stable-alpine'
    container_name: nginx
    ports:
      - '8088:80'
    volumes:
      - './backend:/var/www/html'
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - php
      - mysql
    networks:
      - api

  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - '4306:3306'
    volumes:
      - './mysql:/var/lib/mysql'
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - api

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - './backend:/var/www/html'
    working_dir: /var/www/html
    ports:
      - '9000:9000'
    networks:
      - api

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan
    volumes: 
      - ./backend:/var/www/html
    depends_on: 
      - mysql
    working_dir: /var/www/html
    entrypoint: ['/var/www/html/artisan']
    networks: 
      - api
  
  npm: 
    image: node
    container_name: npm
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - api

  composer:
    image: composer
    container_name: composer
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    networks:
      - api

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - '4000:80'
    depends_on: 
      - mysql
    environment:
      - PMA_HOST=mysql
    networks: 
      - api
  
  nuxt:
    image: node
    container_name: nuxt
    volumes:
      - ./frontend:/usr/src/nuxt
    working_dir: /usr/src/nuxt
    ports:
      - "3000:3000"
    environment:
      HOST: 0.0.0.0
    command: npm run dev
    networks:
      - client
  