version: '3'
networks:
  laravel: null
services:
  nginx:
    image: 'nginx:stable-alpine'
    container_name: nginx
    ports:
      - '8088:80'
    volumes:
      - './src:/var/www/html'
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - php
      - mysql
    networks:
      - laravel
  mysql:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - '4306:3306'
    volumes:
      - './mysql:/var/lib/mysql'
    environment:
      MYSQL_DATABASE: json-api
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - './src:/var/www/html'
    working_dir: /var/www/html/json-api
    ports:
      - '9000:9000'
    networks:
      - laravel

  # composer:
  #   image: composer
  #   container_name: composer
  #   volumes:
  #     - ./src:/var/www/html
  #   working_dir: /var/www/html/laravel-json-api
  #   networks:
  #     - laravel

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - '4000:80'
    depends_on: 
      - mysql
    environment:
      - PMA_HOST=mysql
    networks: 
      - laravel
