version: '3'
networks:
  laravel: null
services:
  nginx:
    image: 'nginx:stable-alpine'
    container_name: nginx
    ports:
      - '8088:80'
    volumes:
      - './src:/var/www/html'
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - php
      - mysql
    networks:
      - laravel
  mysql:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - '4306:3306'
    volumes:
      - './mysql:/var/lib/mysql'
    environment:
      MYSQL_DATABASE: $DATABASE_NAME
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - './src:/var/www/html'
    ports:
      - '9000:9000'
    networks:
      - laravel
