version: "3"

networks:
  default:
    external:
      name: "proxy"

services:
  proxy:
    image: nginx:stable-alpine
    container_name: proxy
    hostname: proxy
    mem_limit: 300m
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ".:/etc/nginx/"
