version: "3"

networks:
  default:
    external:
      name: proxy

services:
  nginx:
    image: "nginx:stable-alpine"
    container_name: api_server
    ports:
      - "8888:80"
    volumes:
      - "../:/var/www/html"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - php
      - mysql

  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - "./mysql:/var/lib/mysql"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: groupeseb
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - "../:/var/www/html"
    working_dir: /var/www/html
    ports:
      - "9000:9000"

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan
    volumes:
      - ../:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ["/var/www/html/artisan"]

  npm:
    image: node
    container_name: npm
    volumes:
      - ../:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["npm"]

  composer:
    image: composer
    container_name: composer
    volumes:
      - ../:/var/www/html
    working_dir: /var/www/html

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - "4000:80"
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    hostname: mailhog
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
